### ISSUE TITLE
`multiple` relations (one to many) are not supported

### ISSUE THREAD

**Issue by gBasil** [david-plugge/typed-pocketbase#11]
Currently, relations seem to only work for Single relations. rather than Multiple relations, as the relation is always singular instead of being an array for Multiple relations.

In other words, instead of being `SomeResponse[]`, the codegen generates `SomeResponse`.

**Comment by david-plugge** [comment]
fixed in https://github.com/david-plugge/typed-pocketbase/commit/19bce54b2162757534cd9a436f56c0d36959ab4f (version 0.0.5)

**Comment by david-plugge** [comment]
use 0.0.6 instead, the actual record types were still wrong in 0.0.5
