### ISSUE TITLE
How to generate types from a url?

### ISSUE THREAD

**Issue by ilbrigz** [david-plugge/typed-pocketbase#14]

**Comment by ilbrigz** [comment]
found it! I'm getting this error though. Hope you could help
```[5708:0804/174545.047:ERROR:networ
k_change_notifier_win.cc(143)] WSA
LookupServiceBegin failed with: 0
[8848:0804/174545.772:ERROR:broker
_win.cc(56)] Error reading broker
pipe: The pipe has been ended. (0x
6D)```

**Comment by david-plugge** [comment]
When does this error occur?

**Comment by ilbrigz** [comment]
![image](https://github.com/david-plugge/typed-pocketbase/assets/32309779/248b0f2f-50b5-4765-9e26-05df4898079a)


.env has
```
POCKETBASE_EMAIL=test@gmail.com
POCKETBASE_PASSWORD=somepwd
```

**Comment by david-plugge** [comment]
The cli does not load the .env by itself. You can use https://www.npmjs.com/package/dotenv-cli for that
