### ISSUE TITLE
Items added through `expand` are not typed

### ISSUE THREAD

**Issue by gBasil** [david-plugge/typed-pocketbase#2]
When fetching data with the following code:
```ts
const results = await pb.collection('events').getList(1, 10, {
  // @ts-ignore It also doesn't have the concept of relations, but I'll make a separate issue for that
  filter: eq('site.slug', slug),
  expand: 'links'
});
```
the `results` variable's type does not have an attribute called `expand`, despite the returned object having it.

**Comment by david-plugge** [comment]
I released a new version with the latest changes, check out by installing `typed-pocketbase@next`. I still need to update the readme but you can _expand_ your collection like so:

```ts
const posts = await db.collection('posts').getFullList({
    expand: expand({
        owner: true,
    }),
});

// nested expand
const posts = await db.collection('posts').getFullList({
    expand: expand({
        owner: {
			profile: true
		},
    }),
});
```

**Comment by david-plugge** [comment]
## INFO

This new version comes with it´s own codegen cli.

```json
{
	"scripts": {
		"gen": "typed-pocketbase -e admin@mail.com -p supersecretpassword"
	}
}
```
If not passed as options, the cli will look for `POCKETBASE_EMAIL` and `POCKETBASE_PASSWORD` environment variables instead.

**Comment by david-plugge** [comment]
Updated README: https://github.com/david-plugge/typed-pocketbase/blob/next/README.md

**Comment by david-plugge** [comment]
Ouh yeah, i forgot to add some column types, will do that tomorrow

**Comment by david-plugge** [comment]
> How exactly would I make types with expansions, to use with things like function arguments?

Can you give an example on what you're trying to achieve?

**Comment by david-plugge** [comment]
Ah got it. You need to make use of `TypedRecord` (not yet exported)

```ts
function doSomething(
	posts: TypedRecord<PostsRecord, {
		owner: TypedRecord<UsersRecord, {
			profile: TypedRecord<ProfilesRecord>
		}>
	}>
) {}
```

**Comment by david-plugge** [comment]
version 0.0.3-next.2 exposes `TypedRecord`!
