### ISSUE TITLE
how to use outsideof inline pocketbase query

### ISSUE THREAD

**Issue by tigawanna** [david-plugge/typed-pocketbase#23]
Thanks for the awesome package , 
Am here asking for some guidance on what generics to pass into the various helper methods.
Am trying to compose the filters and sort and pass them into components dynamically, how do I type them?
for example 
Am trying to pass this 
```ts
const following_filter = or(
  and(["user_a.id", "=", profile_id], ["user_a_follow_user_b", "=", "yes"]),
  and(["user_b.id", "=", profile_id], ["user_b_follow_user_a", "=", "yes"]),
);
```
into  this 
```ts
        PB
          .collection("pocketbook_friendship")
          .getList(pageParam?.page,12,{
            filter: or(    
             and( ["user_a.id", "=",profile_id],),
              ["user_b.id", "=", profile_id]
              )
        })
```
what generic do I pass into it?  I see it's supposed to be T extends BaseRecord, so should I pass in the Collection or CollectionResponse ?
hovering the pocketbase client gave me this 

``` ts
TypedPocketBase<Schema>.collection<"pocketbook_friendship">(idOrName: "pocketbook_friendship"): TypedRecordService<PocketbookFriendshipCollection>
```
I had the same difficulty with sort too, is there a cheat sheet to what generic to pass into these helpers

**Comment by david-plugge** [comment]
Hi, glad you like it :)

Interesting use case, i havent thought about that.
I think it makes sense to only provide this kind of type helpers for `filter` and `sort`, as it is impossible to resolve the return type for dynamic `fields` and `expand` options.

What do you think?

**Comment by tigawanna** [comment]
I some what got them working but I forgot how , the parts I remember was passing the type of the collection and type the expanded collection  , sort was the tricky one.
 
My biggest stumbling block was that it was all guess work since , generic  T,S and R are not very descriptive . 
It might be too much work t but if possible would be great to document what the generics required are for , in one of the ones I got working you needed to provide TypedRecord<Collection> it took me a while to guess that one and I don't even remember how I used it and it's buried somewhere in my commits. The library is super awesome though and thanks for the great work

**Comment by tigawanna** [comment]
Helper types would be great too
