### ISSUE TITLE
Type URL and FILE to be strings on Response interface 

### ISSUE THREAD

**Issue by tigawanna** [david-plugge/typed-pocketbase#27]
Hi, this is more of a feature request as it looks like a some changes are ongoing, I feel like it would make sense to have File and URL type in the response interfaces be strings because they'll come down the wire as strings , which leads to typescript complaining if you try to form a url to the actual file with the file field  which is supposed to be a string but typescript thinks is a File ,same issue with the URL tupe in the response, it makes sense in create and update interfaces though

**Comment by david-plugge** [comment]
Should be fixed in `0.1.0`!

**Comment by tigawanna** [comment]
🙏 thanks for the great work

**Comment by david-plugge** [comment]
If you can verify that this issue is resolved, feel free to close it :)
