### ISSUE TITLE
No concept of nested filters

### ISSUE THREAD

**Issue by gBasil** [david-plugge/typed-pocketbase#3]
The package doesn't seem to have the concept of nested filters. `@ts-ignore` must be used on the following in order to avoid a type error that `Argument of type '"site.slug"' is not assignable to parameter of type 'keyof SystemFields | keyof EventsRecord'.`
```ts
const results = await pb.collection('events').getList(1, 10, {
  // @ts-ignore It also doesn't have the concept of relations, but I'll make a separate issue for that
  filter: eq('site.slug', 'catgirls')
});
```
`site` here is a relation to an item in another collection, and `slug` is a text property on the items in the `site` collection.

Thank you for the fantastic library!

**Comment by david-plugge** [comment]
The latest version supports nested filters, check out by installing `typed-pocketbase@next`. I still need to update the readme but you can filter your data like so:

```ts
const posts = await db.collection('posts').getFullList({
    filter: eq('post.email', 'user@mail.com')
});
```

It works up to 6 levels (including the top level that doesn´t need to collection prefix) which aligns with pocketbase.

**Comment by david-plugge** [comment]
https://github.com/david-plugge/typed-pocketbase/blob/next/README.md
