### ISSUE TITLE
Subscribe and unsubscribe missing from API

### ISSUE THREAD

**Issue by JaCoB1123** [david-plugge/typed-pocketbase#30]
Hi David,

I introduced typed-pocketbase into a project and really enjoy it so far. Thanks for the awesome project.

I noticed that subscribe and unsubscribe have been removed from the API because of the pocketbase 0.20.0 update. I'd love to see this again - I'm currently working around it by forgoing type checking.

Thanks.

**Comment by david-plugge** [comment]
Hi @JaCoB1123, glad you like it!

Good catch, i didn't notice that... Haven't used my own library for a while now.
But i'm currently working on a custom client, which extends the default one. This makes it possible to get rid of `createOptions` and the overly complicated `fields` and `expand` stuff.

You can check it out if you want, but i think the subscription stuff is still missing, will add that in the next release!
[0.1.0-pre.0](https://www.npmjs.com/package/typed-pocketbase/v/0.1.0-pre.0)

**Comment by david-plugge** [comment]
Subscriptions are now available in version [0.1.0-pre.2](https://www.npmjs.com/package/typed-pocketbase/v/0.1.0-pre.2). Give it a try and let me know if it works for you

**Comment by JaCoB1123** [comment]
I just did a test run with 0.1.0-pre.3 and subscriptions seem to be working now, thanks!
I'm having trouble with expands though, I guess that's still a work in progress? My expand-field was empty in all of my tests.

**Comment by JaCoB1123** [comment]
I noticed another issue with sorts and filters. It seems the npm package is somehow inconsistent:
in dist/index.js the sort code is still the old version. in src/client.ts the code is correct.
Although the assignment of filters seems to be missing in prepareOptions so filters are not doing anything right now.

**Comment by david-plugge** [comment]
Thanks for pointing out, seems like i forgot to run build before publishing!
Filters should now be handled correct.

**Comment by david-plugge** [comment]
Should be fixed in `0.1.0`!

**Comment by JaCoB1123** [comment]
Looking good now, thanks!

**Comment by shyakadavis** [comment]
Hi;

There's no Discussions tab, and an issue didn't feel right. Anyway, I wanted to ask for help with the Sub and Unsub API.

I couldn't figure it out, so anyone mind sharing a working snippet? (Didn't find an example in the README 🙁)

Also, @david-plugge, I don't know if you use Svelte/Kit regularly, but do you mind sharing how you would achieve real-time sub/fetching on the client?

Trying to move away from SSR for some use-cases, but have no idea how to fetch "correctly" on the client, in that I want to fetch some data, and place in into a store.

Thank you.
