### ISSUE TITLE
New codegen (`next` branch) generating invalid types

### ISSUE THREAD

**Issue by gBasil** [david-plugge/typed-pocketbase#5]
![image](https://github.com/david-plugge/typed-pocketbase/assets/57513430/6af8dde4-4d0e-4bd5-9fd0-605a72eb488b)

This seems to happen to `file` relations, as this same syntax error (`files.icon`) shows up twice in the generated output.

**Comment by david-plugge** [comment]
Should be fixed in the latest version

**Comment by david-plugge** [comment]
To give some context, i added support for typed file thumbs aswell so you always know the available options. Not sure if it´s worth though, since you need to pass the field name to `getUrl`...

```ts
const post = ...

db.files.getUrl({
	collectionId: 'posts',
	id: post.id,
	field: 'preview' // this is neccessary at the moment
}, post.preview, {
	thumb: '144x0' // this is typed now
})
```
