### ISSUE TITLE
Create a new query client instead of modifying the types

### ISSUE THREAD

**Issue by david-plugge** [david-plugge/typed-pocketbase#6]
The current version adds typesafety by overwriting the types in the JS SDK and providing helper functions like `expand` or `fields`.

Instead it could be better to create a new client:

```ts
import PocketBase from 'pocketbase';
import TypedPocketBase from './generated-pocketbase-client';

const pb = new PocketBase();

const db = new TypedPocketBase(pb);

// (looks a lot like the prisma client)
db.posts.getFullList({
	fields: {
		title: true,
		content: true,
	},
	sort: [ '+date' ],
	filter: or({
		user: {
			role: eq('admin')
		}
	}, {
		published: true
	}),

	// note that expanding doesnt work when selecting fields
	expand: {
		user: true
	}
});
```

Thoughts?

**Comment by david-plugge** [comment]
It´s also possible to extend the pocketbase client directly and add this functionality on a new property so you don´t even need to import anything from `pocketbase`

```ts
import TypedPocketBase from './generated-pocketbase-client';

const pb = new TypedPocketBase();

// not sure about the property name...
pb._.posts.getFullList(...)

// prefix all collections with a symbol
pb.$posts.getFullList(...)

// or maybe even something like this
pb.from('posts').getFullList(...)
```

**Comment by david-plugge** [comment]
This would also make it possible to modify data before returning it to the user. In other words, we could parse a `date` columns value to a `Date` object!

**Comment by mateuszlewko** [comment]
This looks great! Thanks for creating this awesome library.
