### ISSUE TITLE
`date` values for `update` typed improperly

### ISSUE THREAD

**Issue by gBasil** [david-plugge/typed-pocketbase#9]
The `update` function (`pb.collection('collectionName').update`) says that `date` fields require `string` inputs. However, passing a `Date` object into it works despite the type system marking it as incorrect. I am not sure if strings can be passed into the fields. It is also important to note that the `date` field returned by various fetching methods is in the form of a `string`.

This workaround works:
```ts
await pb.collection('someCollection').update(id, {
	date: new Date(dateString) as unknown
});
```

**Comment by david-plugge** [comment]
Added support in version 0.0.4 , thanks for reporting the issue
